IconTheme(data: IconThemeData(color: Colors.red,size: 30), child:FaIcon(icons)),
SizedBox(height: 5,),
Text(ORGname,style: TextStyle(fontSize: 12,color: Colors.black), ),
SizedBox(height: 5,),
Text(matchName,style: TextStyle(fontSize: 12,color: Colors.white), ),
SizedBox(height: 5,),
Text(Timing,style: TextStyle(fontSize: 12,color: Colors.white), ),
SizedBox(height: 5,),
Text(Lineup,style: TextStyle(fontSize: 12,color: Colors.black), ),